###
GET http://localhost:9003/users/esteput HTTP/1.1

###
POST http://localhost:9003/users HTTP/1.1
Content-Type: application/json

{

    "NombreCompleto":"Alexandro",
    "Username":"Prueba Time",
    "Password":"lehr3456",
    "Rol":"2",
    "Token":"devin33@gmail.com",
    "TokenTimeStamp": "1"
  

    
}

###
PUT http://localhost:9003/users/639a9d355627e5649811d417 HTTP/1.1
Content-Type: application/json


{
    "NombreCompleto":"Bebitho",
    "Username":"Este Put",
    "Password":"lehr3456",
    "Rol":"2",
    "Token":"devin33@gmail.com",
    "TokenTimeStamp": "1"
   
}

### 
DELETE http://localhost:9003/users/63922db755b5fe59c0d5e048 HTTP/1.1


###
POST http://localhost:9003/token HTTP/1.1
Content-Type: application/json

{

    "Token": "e25c6c394b98c54efbe7f730d5b57cdc",
    "Username":"esteput",
    "Rol":"2"
    
    

    
}



###
POST http://localhost:9003/login HTTP/1.1
Content-Type: application/json

{

 "Username":"esteput",
 "Password":"lehr3456"

    
}